name: Test
on:
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:15-alpine

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Running tests
        run: yarn test

      - name: Publishing
        run: yarn publish
